# Generated by Django 5.2.6 on 2025-12-03 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0002_directmessage_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="description",
            field=models.CharField(
                default="testing the description implementatino for the listings",
                max_length=200,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="listing",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
