# Generated by Django 5.2.6 on 2025-12-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0003_listing_description_alter_listing_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="driver",
            name="username",
            field=models.CharField(default="ha", max_length=30),
        ),
    ]
