# Generated by Django 5.2.6 on 2025-12-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0005_alter_driver_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="username",
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
