# Generated by Django 5.2.6 on 2025-12-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0007_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.DecimalField(decimal_places=0, max_digits=1),
        ),
    ]
