# Generated by Django 5.2.6 on 2025-12-04 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0008_alter_rating_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="style",
            field=models.CharField(
                choices=[
                    ("coupe", "Coupe"),
                    ("sedan", "Sedan"),
                    ("hatch", "Hatchback"),
                    ("wagon", "Wagon"),
                    ("suv", "SUV"),
                    ("truck", "Truck"),
                    ("bike", "Motorcycle"),
                ],
                default="",
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
