# Generated by Django 5.2.6 on 2025-12-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0009_car_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="style",
            field=models.CharField(
                choices=[
                    ("coupe", "Coupe"),
                    ("vert", "Convertible"),
                    ("sedan", "Sedan"),
                    ("hatch", "Hatchback"),
                    ("wagon", "Wagon"),
                    ("suv", "SUV"),
                    ("truck", "Truck"),
                    ("bike", "Motorcycle"),
                ],
                max_length=15,
            ),
        ),
    ]
