# Generated by Django 5.2.6 on 2025-12-04 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0010_alter_car_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="ownership_type",
            field=models.CharField(
                choices=[
                    ("Primary", "Primary"),
                    ("Secondary", "Secondary"),
                    ("Track", "Track"),
                    ("Drag", "Drag"),
                    ("Drift", "Drift"),
                    ("Rally", "Rally"),
                ],
                max_length=9,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="style",
            field=models.CharField(
                choices=[
                    ("Coupe", "Coupe"),
                    ("Convertible", "Convertible"),
                    ("Sedan", "Sedan"),
                    ("Hatchback", "Hatchback"),
                    ("Wagon", "Wagon"),
                    ("SUV", "SUV"),
                    ("Truck", "Truck"),
                    ("Motorcycle", "Motorcycle"),
                ],
                max_length=15,
            ),
        ),
    ]
