# Generated by Django 5.2.6 on 2025-12-04 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0011_alter_car_ownership_type_alter_car_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to="partout.driver",
            ),
        ),
    ]
