# Generated by Django 5.2.6 on 2025-12-04 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0012_alter_message_sender"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="receiver",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_messages",
                to="partout.driver",
            ),
        ),
    ]
