# Generated by Django 5.2.6 on 2025-12-08 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0015_driver_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="is_read",
        ),
    ]
