# Generated by Django 5.2.6 on 2025-12-09 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0016_remove_message_is_read"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="driver",
        ),
        migrations.RenameField(
            model_name="like",
            old_name="user",
            new_name="driver",
        ),
        migrations.AlterField(
            model_name="listing",
            name="condition",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Like New", "Like New"),
                    ("Used", "Used"),
                    ("Abused", "Abused"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="part_type",
            field=models.CharField(
                choices=[
                    ("Engine", "Engine"),
                    ("Transmission", "Transmission"),
                    ("Exhaust", "Exhaust"),
                    ("Wheels", "Wheels"),
                    ("Suspension", "Suspension"),
                    ("Exterior", "Exterior"),
                    ("Interior", "Interior"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                    ("Sold", "Sold"),
                    ("Not Available", "Not Available"),
                ],
                default="active",
            ),
        ),
        migrations.AlterField(
            model_name="offer",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Declined", "Declined"),
                ],
                default="Pending",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("listing", "driver")},
        ),
    ]
