# Generated by Django 5.2.6 on 2025-12-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "partout",
            "0017_rename_author_comment_driver_rename_user_like_driver_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="savedlisting",
            old_name="user",
            new_name="driver",
        ),
        migrations.AlterField(
            model_name="listing",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                    ("Sold", "Sold"),
                    ("Not Available", "Not Available"),
                ],
                default="Active",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedlisting",
            unique_together={("listing", "driver")},
        ),
    ]
