# Generated by Django 5.2.6 on 2025-12-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partout", "0019_alter_rating_rating_delete_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.PositiveIntegerField(
                choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
            ),
        ),
    ]
